{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build\
WORKDIR /src\
COPY BVRelayServer.csproj ./\
RUN dotnet restore\
COPY . ./\
RUN dotnet publish -c Release -o /app/publish\
\
FROM mcr.microsoft.com/dotnet/aspnet:8.0\
WORKDIR /app\
COPY --from=build /app/publish .\
ENV ASPNETCORE_URLS=http://+:8080\
EXPOSE 8080\
ENTRYPOINT ["dotnet", "BVRelayServer.dll"]\
}